### ISSUE TITLE
companion_krylov not used

### ISSUE THREAD

**Issue by luchris429** [HazyResearch/spacetime#2]
Hello,

This work is super cool! One question I have is that the code in `companion_krylov.py` seems to more closely match what's written in the paper (Algorithm 1). However, it looks like `companion.py` does not use it. It instead uses the much simpler `krylov.py`. 

Is there a particular reason for this or am I misunderstanding the code paths?

**Comment by thinhngo-x** [comment]
Hi @luchris429 , i have the same question when reviewing the code. Could it be due to the inefficiency of the FFT? Have you tried benchmarking the two implementations to see which one is more efficient?

**Comment by mzio** [comment]
Hi @luchris429 and @thinhngo-x , sorry for the late replies.. I'm getting notifications for these now. 

The main model code as-is was meant to be a simplified + instructive treatment for the SSMs (as opposed to the other dev repos for H3 and S4 at the time); showing in-code what the recurrent and convolutional views amount to, etc... 

So I left in the `CompanionSSM` class and `matrix_power` to show in-code the rollout.
* However, for benchmarking, we use `companion_krylov.py` as a more efficient substitute. 
* For reference on how to use / how benchmarking was done please see https://github.com/HazyResearch/spacetime/blob/7b7398caf3636d11dde4606eaeb96ea557aeee0e/model/functional/companion_krylov.py#L69
